# Generated by Django 3.2.2 on 2021-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='SOME STRING', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
