# Generated by Django 3.2.2 on 2022-02-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20220131_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Enter your name', max_length=200)),
                ('Address', models.CharField(default='Enter the deliver address', max_length=200)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
