# Generated by Django 3.2.2 on 2022-02-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20220204_0815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
